name: Formal verification

on:
  push:
    branches:
      - master
      - release-v*
  pull_request: {}
  workflow_dispatch: {}

inputs:
  pip-version:
    default: '3.10'
  java-version:
    default: '11'
  solc-version:
    default: '0.8.19'

jobs:
  list-scripts:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "matrix=$(echo -n certora/scripts/*.sh | jq -Rsc 'split(" ")')" >> "$GITHUB_OUTPUT"

  verify:
    runs-on: ubuntu-latest
    needs: list-scripts
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ pip-version }}
          cache: 'pip'
      - name: Install java
        uses: actions/setup-java@v1
        with:
          java-package: 'jre'
          java-version: ${{ java-version }}
      - name: Install certora
        run: pip install certora-cli
      - name: Install solc
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v${{ solc-version }}/solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc
          chmod +x /usr/local/bin/solc
      - name: Verify rule ${{ matrix.params }}
        run: |
          make -C certora apply
          bash ${{ matrix.params }}
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        params: ${{ fromJson(needs.list-scripts.outputs.matrix) }}
